#! /bin/bash
sudo apt-get update
wget https://download.anydesk.com/rpi/anydesk_6.1.0-1_armhf.deb 
sudo dpkg -i anydesk_6.1.0-1_armhf.deb
sudo apt-get install chromium-browser --yes
python ../setup.py install

